// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';


function make(point) {
  return point;
}

function $$location(apple) {
  return apple;
}

exports.make = make;
exports.$$location = $$location;
/* No side effect */
