// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Random = require("bs-platform/lib/js/random.js");
var Apple$Snake = require("./Apple.bs.js");
var Snake$Snake = require("./Snake.bs.js");
var GameRun$Snake = require("./GameRun.bs.js");
var GameWorld$Snake = require("./GameWorld.bs.js");

function _nextApple(param) {
  return Apple$Snake.make(/* record */[
              /* x */Random.$$int(40),
              /* y */Random.$$int(40)
            ]);
}

function _makeSnake(param) {
  return Snake$Snake.make(/* record */[
              /* x */20,
              /* y */20
            ], /* Left */0);
}

function _makeGameWorld(param) {
  return GameWorld$Snake.make(/* record */[
              /* width */40,
              /* height */40
            ], /* Alive */0, _makeSnake(/* () */0), _nextApple(/* () */0), _nextApple);
}

function makeGameRun(param) {
  var partial_arg = _makeGameWorld(/* () */0);
  return (function (param) {
      return GameRun$Snake.run(partial_arg, param);
    });
}

exports.makeGameRun = makeGameRun;
/* No side effect */
