// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

function _findContext(canvasId) {
  var match = document.getElementById(canvasId);
  if (match == null) {
    return /* Error */Block.__(1, ["Could not find canvas element: " + canvasId]);
  } else {
    return /* Ok */Block.__(0, [match.getContext("2d")]);
  }
}

function _keyPressOfString(key) {
  switch (key) {
    case "ArrowDown" : 
        return /* ArrowDown */3;
    case "ArrowLeft" : 
        return /* ArrowLeft */0;
    case "ArrowRight" : 
        return /* ArrowRight */1;
    case "ArrowUp" : 
        return /* ArrowUp */2;
    default:
      return undefined;
  }
}

function _jsColor(color) {
  switch (color) {
    case 0 : 
        return "white";
    case 1 : 
        return "green";
    case 2 : 
        return "red";
    case 3 : 
        return "gray";
    case 4 : 
        return "black";
    
  }
}

function _listen(handleKey) {
  document.addEventListener("keydown", (function ($$event) {
          var match = _keyPressOfString($$event.key);
          if (match !== undefined) {
            return Curry._1(handleKey, match);
          } else {
            return /* () */0;
          }
        }));
  return /* () */0;
}

function _setColor(context, color) {
  context.fillStyle = _jsColor(color);
  return /* () */0;
}

function _fillRect(context, $$location, dim) {
  context.fillRect($$location[/* x */0], $$location[/* y */1], dim[/* width */0], dim[/* height */1]);
  return /* () */0;
}

function _make(context, period) {
  return /* record */[
          /* start */(function (param) {
              var period$1 = period;
              var action = param;
              var intervalId = setInterval(action, period$1);
              return (function (param) {
                  clearInterval(intervalId);
                  return /* () */0;
                });
            }),
          /* listen */_listen,
          /* setColor */(function (param) {
              return _setColor(context, param);
            }),
          /* setTextAlign */(function (param) {
              var context$1 = context;
              context$1.textAlign = "center";
              return /* () */0;
            }),
          /* setFont */(function (param) {
              var context$1 = context;
              context$1.font = "30px Comic Sans MS";
              return /* () */0;
            }),
          /* fillRect */(function (param, param$1) {
              return _fillRect(context, param, param$1);
            }),
          /* fillText */(function (param, param$1) {
              var context$1 = context;
              var text = param;
              var $$location = param$1;
              context$1.fillText(text, $$location[/* x */0], $$location[/* y */1]);
              return /* () */0;
            }),
          /* clear */(function (param) {
              var context$1 = context;
              var color = param;
              _setColor(context$1, color);
              return _fillRect(context$1, /* record */[
                          /* x */0,
                          /* y */0
                        ], /* record */[
                          /* width */context$1.canvas.width,
                          /* height */context$1.canvas.height
                        ]);
            })
        ];
}

function make(canvasId, period) {
  var match = _findContext(canvasId);
  if (match.tag) {
    return /* Error */Block.__(1, [match[0]]);
  } else {
    return /* Ok */Block.__(0, [_make(match[0], period)]);
  }
}

exports.make = make;
/* No side effect */
