// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var JsRuntimeContext$Snake = require("./JsRuntimeContext.bs.js");

function makeRuntimeContext(param) {
  return JsRuntimeContext$Snake.make("js-canvas", 200);
}

exports.makeRuntimeContext = makeRuntimeContext;
/* No side effect */
