// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Apple$Snake = require("../src/Apple.bs.js");

Jest.describe("location", (function (param) {
        return Jest.test("returns the location of the apple", (function (param) {
                      var apple = Apple$Snake.make(/* record */[
                            /* x */5,
                            /* y */4
                          ]);
                      return Jest.Expect[/* toEqual */12](/* record */[
                                  /* x */5,
                                  /* y */4
                                ], Jest.Expect[/* expect */0](Apple$Snake.$$location(apple)));
                    }));
      }));

/*  Not a pure module */
